name = "Earley"
version = "0.1.0"
defaultTargets = ["Earley"]
testRunner = "EarleyTest"

[leanOptions]
autoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.2"

[[lean_lib]]
name = "Earley"

[[lean_lib]]
name = "EarleyTest"

[[lean_exe]]
name = "Bench"
