/-
Copyright (c) 2026 Daniel Soukup. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Daniel Soukup
-/
module
public import Earley.Model
public import Earley.Proofs.Model
public import Earley.Recognizer
public import Earley.Proofs.Recognizer
public import Earley.CachedRecognizerPointers

/-!
This module houses the correctness proofs for the
   _____           _              _            _____                 _
  / ____|         | |            | |          |_   _|               | |
 | |     __ _  ___| |__   ___  __| |  ______    | |  _ __ ___  _ __ | |
 | |    / _` |/ __| '_ \ / _ \/ _` | |______|   | | | '_ ` _ \| '_ \| |
 | |___| (_| | (__| | | |  __/ (_| |           _| |_| | | | | | |_) | |
  \_____\__,_|\___|_| |_|\___|\__,_|          |_____|_| |_| |_| .__/|_|
                                                              | |
                                                              |_|

The proofs follow the work from Rau et Nipkow:
https://doi.org/10.4230/LIPIcs.ITP.2024.31

To verify the correctness of the implementation,
we first prove correctness of the model - an inductive definition / judgements.
Then we can refine the proofs to the naive list-based implementation by proving
that the items in the bins correspond exactly to the EarleyItems generated by the judgements.
We can extend this result to the optimized version by proving that
the optimized version computes the exact same bins.
-/

@[expose] public section

namespace Earley
namespace Proofs
namespace CachedRecognizerPointers

-- TODO: I most likely dont need most of these for this one.
open Earley.Model
open Earley.Model.EarleyItem
open Earley.Proofs.Model
open Earley.Recognizer
open Earley.CachedRecognizerPointers
open Earley.Proofs.Recognizer
open Earley.Proofs.Finiteness
open Utils
open ContextFreeRule
open ContextFreeGrammar

variable {T N : Type} [BEq T] [LawfulBEq T] [BEq N] [LawfulBEq N] [LawfulBEq (EarleyItem T N)]
  [Hashable N] [Hashable (EarleyItem T N)]

-- unclear if I actually need this set indirection
@[grind]
def earleyCachedSet (G : ContextFreeGrammarList T N) (w : Array T) : Set (EarleyItem T N) :=
  rawList (earleyCached G w).bins |> setOfBins

lemma earleyCachedSet_eq_earleyListSet (G : ContextFreeGrammarList T N) (w : Array T) :
    earleyCachedSet G w = earleyListSet G w.toList := by
  simp only [earleyListSet, earleyCachedSet]
  --have := earleyBinsListSet_sub_model w h w.length (by lia)
  --grind
  sorry

section Soundness
/--
The soundness criteria for the list implementation:
Given a finished item for a word within the set, the grammar has to be able to generate that word.
-/
public theorem soundnessEarleyCached {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] [Hashable G.NT] [Hashable (EarleyItem T G.NT)]
    (w : Array T) {Gₗ : ContextFreeGrammarList T G.NT} (h : CFGEqCFGₗ G Gₗ)
    (hex : recognizeCached Gₗ w) : G.Generates (mapT w.toList) := by
  apply soundnessEarleyList w.toList h
  simp only [recognizeCached, decide_eq_true_eq] at hex
  rcases hex with ⟨x, ⟨hmem, hfin⟩⟩
  simp only [recognizeList, Array.length_toList, decide_eq_true_eq]
  use x
  refine ⟨?_, by grind⟩
  have := earleyCachedSet_eq_earleyListSet Gₗ w
  sorry

end Soundness

section Completeness

public theorem completenessEarleyCached {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] [Hashable G.NT] [Hashable (EarleyItem T G.NT)]
    (w : Array T) {Gₗ : ContextFreeGrammarList T G.NT} (h : CFGEqCFGₗ G Gₗ) (heps : isEpsilonFree G)
    (hgen : G.Generates (mapT w.toList)) : recognizeCached Gₗ w := by
  have hex := completenessEarleyList w.toList h heps hgen
  simp only [recognizeCached, decide_eq_true_eq]
  simp only [recognizeList, Array.length_toList, decide_eq_true_eq] at hex
  rcases hex with ⟨x, ⟨hmem, hfin⟩⟩
  use x
  refine ⟨?_, by grind⟩
  have := earleyCachedSet_eq_earleyListSet Gₗ w
  sorry

end Completeness

/--
The correctness criteria for the recognizer.
A word can be generated from the grammar iff the algorithm recognizes the word.
-/
public theorem correctnessEarleyCached {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] [Hashable G.NT] [Hashable (EarleyItem T G.NT)]
    (w : Array T) {Gₗ : ContextFreeGrammarList T G.NT} (h : CFGEqCFGₗ G Gₗ)
    (heps : isEpsilonFree G) : G.Generates (mapT w.toList) ↔ recognizeCached Gₗ w := by
  grind [soundnessEarleyCached, completenessEarleyCached]

end CachedRecognizerPointers
end Proofs
end Earley
