/-
Copyright (c) 2026 Daniel Soukup. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Daniel Soukup
-/
module
public import Earley.Model
public import Earley.Fixpoint
public import Earley.Proofs.Model

/-!
This module houses the correctness proofs for the
  ______ _                  _       _      _____      _
 |  ____(_)                (_)     | |    / ____|    | |
 | |__   ___  ___ __   ___  _ _ __ | |_  | (___   ___| |_
 |  __| | \ \/ / '_ \ / _ \| | '_ \| __|  \___ \ / _ \ __|
 | |    | |>  <| |_) | (_) | | | | | |_   ____) |  __/ |_
 |_|    |_/_/\_\ .__/ \___/|_|_| |_|\__| |_____/ \___|\__|
               | |
               |_|

The proofs follow the work from Rau et Nipkow:
https://doi.org/10.4230/LIPIcs.ITP.2024.31

To verify the correctness of the implementation,
we first prove correctness of the model - an inductive definition / judgements.
Then we can refine the proofs to a fixpoint-based implementation by proving
that the items in the Sets correspond exactly to the EarleyItems generated by the judgements,
then refine it further to the actual bins with the same idea.

TODO: Rename a ton of lemmas since I forgot about the style in the middle /o\
      https://leanprover-community.github.io/contribute/naming.html
-/

@[expose] public section

namespace Earley
namespace Proofs
namespace Fixpoint

open Earley.Model
open Earley.Model.EarleyItem
open Earley.Proofs.Model
open Earley.Fixpoint
open Utils
open ContextFreeRule
open ContextFreeGrammar

variable {T N : Type}

/--
Returns the subset of `I` where prevSymbol is a terminal.

Denotes the subset of I that forms the k-th base of a bin,
meaning the subset of I containing only items of the form A → αa • β, i, j,
where a is a terminal symbol preceding the dot.
TODO: I dont see how the following quote would be correct with this definition:
      `If k is zero, base ω I 0 consists of all initial items S G → •α, 0, 0`
-/
def base (I : Set (EarleyItem T N)) (w : List (Symbol T N)) (k : Nat) : Set (EarleyItem T N) :=
  { x ∈ I | x.endIdx = k ∧ k > 0 ∧ prevSymbol x = w[k-1]?}

section Soundness

/--
The set generated by the fixpoint .init algorithm is a subset of the one of the model.
-/
public theorem initFixpoint_sub_EarleySet (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) : initFixpoint G ⊆ EarleySet G w := by
  intro x ⟨hpos,hs,he,hmemx,hstart⟩
  have hx : x = ⟨x.rule, x.position, x.startIdx, x.endIdx⟩ := by simp
  rw [hx]
  simp only [hpos, hs, he]
  apply EarleySet.init x.rule hmemx hstart

/--
The set generated by the fixpoint .scan algorithm is a subset of the one of the model.
-/
public theorem scanFixpoint_sub_EarleySet (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (I : Set (EarleyItem T G.NT)) (k : Nat)
    (hsub : I ⊆ EarleySet G w) : scanFixpoint I w k ⊆ EarleySet G w := by
  intro y h
  simp only [scanFixpoint, Set.mem_setOf_eq] at h
  if hk : k < w.length then
    have := h y w[k]
    sorry
  else
    sorry

  --| scan (x : EarleyItem T G.NT) (rule : ContextFreeRule T G.NT) (pos i j : Nat)
  --    (a : Symbol T G.NT) (hx : x = ⟨rule,pos,i,j⟩) (hmem : x ∈ EarleySet G w)
  --    (hbounds : j < w.length) (hw : w[j] = a) (hnext : nextSymbol x = some a) :
  --    EarleySet G w ⟨rule,pos+1,i,j+1⟩
  --apply EarleySet.scan x x.rule

/--
The set generated by the fixpoint algorithm is a subset of the one of the model.
-/
public theorem earleyFixpoint_sub_EarleySet (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (hw : isWord G w) :
    earleyFixpoint G w ⊆ EarleySet G w := by
  sorry

/--
The soundness criteria for the fixpoint version of the recognizer.
-/
public theorem soundnessEarleyFixpoint (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (hw : isWord G w) (hgen : G.Generates w) :
    ∃ x ∈ earleyFixpoint G w, isFinished G.initial w x := by
  sorry

end Soundness

section Completeness

/--
The set of the model is a subset of the one generated by the fixpoint algorithm.
-/
public theorem EarleySet_sub_earleyFixpoint (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (hw : isWord G w) :
    EarleySet G w ⊆ earleyFixpoint G w := by
  sorry

/--
The completeness criteria for the fixpoint version of the recognizer.
-/
public theorem completenessEarleyFixpoint (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (hw : isWord G w) (hgen : G.Generates w) :
    ∃ x ∈ earleyFixpoint G w, isFinished G.initial w x := by
  sorry

end Completeness

/--
The set of the model is identical to the one generated by the fixpoint algorithm.
-/
public theorem EarleySet_eq_earleyFixpoint (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (hw : isWord G w) :
    EarleySet G w = earleyFixpoint G w := by
  have hsub1 := EarleySet_sub_earleyFixpoint G w hw
  have hsub2 := earleyFixpoint_sub_EarleySet G w hw
  apply Set.eq_of_subset_of_subset hsub1 hsub2

/--
The correctness criteria for the fixpoint version of the recognizer.

A word can be generated from the grammar
iff there exists a finished item within the corresponding fixpoint-iterated Set.
-/
public theorem correctnessEarleyFixpoint {G : ContextFreeGrammar T} [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (hw : isWord G w) : G.Generates w ↔
    ∃ x ∈ earleyFixpoint G w, isFinished G.initial w x := by
  grind [EarleySet_eq_earleyFixpoint, Model.correctnessEarleyModel]

end Fixpoint
end Proofs
end Earley
