/-
Copyright (c) 2026 Daniel Soukup. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Daniel Soukup
-/
module
public import Earley.Model
public import Earley.Fixpoint
public import Earley.Proofs.Model

/-!
This module houses the correctness proofs for the
  ______ _                  _       _      _____      _
 |  ____(_)                (_)     | |    / ____|    | |
 | |__   ___  ___ __   ___  _ _ __ | |_  | (___   ___| |_
 |  __| | \ \/ / '_ \ / _ \| | '_ \| __|  \___ \ / _ \ __|
 | |    | |>  <| |_) | (_) | | | | | |_   ____) |  __/ |_
 |_|    |_/_/\_\ .__/ \___/|_|_| |_|\__| |_____/ \___|\__|
               | |
               |_|

The proofs follow the work from Rau et Nipkow:
https://doi.org/10.4230/LIPIcs.ITP.2024.31

To verify the correctness of the implementation,
we first prove correctness of the model - an inductive definition / judgements.
Then we can refine the proofs to a fixpoint-based implementation by proving
that the items in the Sets correspond exactly to the EarleyItems generated by the judgements,
then refine it further to the actual bins with the same idea.

TODO: Rename a ton of lemmas since I forgot about the style in the middle /o\
      https://leanprover-community.github.io/contribute/naming.html
-/

@[expose] public section

namespace Earley
namespace Proofs
namespace Fixpoint

open Earley.Model
open Earley.Model.EarleyItem
open Earley.Proofs.Model
open Earley.Fixpoint
open Utils
open ContextFreeRule
open ContextFreeGrammar

variable {T N : Type}

/--
Returns the subset of `I` where prevSymbol is a terminal.

Denotes the subset of I that forms the k-th base of a bin,
meaning the subset of I containing only items of the form A → αa • β, i, j,
where a is a terminal symbol preceding the dot.
TODO: I dont see how the following quote would be correct with this definition:
      `If k is zero, base ω I 0 consists of all initial items S G → •α, 0, 0`
-/
def base (I : Set (EarleyItem T N)) (w : List (Symbol T N)) (k : Nat) : Set (EarleyItem T N) :=
  { x ∈ I | x.endIdx = k ∧ k > 0 ∧ prevSymbol x = w[k-1]?}

section Soundness

public theorem initFixpoint_sub_EarleySet (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) : initFixpoint G ⊆ EarleySet G w := by
  intro x ⟨r, hx, hmemx, hstart⟩
  rw [hx]
  apply EarleySet.init r hmemx hstart

public theorem scanFixpoint_sub_EarleySet (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (I : Set (EarleyItem T G.NT)) (k : Nat)
    (hsub : I ⊆ EarleySet G w) : scanFixpoint I w k ⊆ EarleySet G w := by
  intro y h
  simp only [scanFixpoint, Set.mem_setOf_eq] at h
  if hk : k < w.length then
    rcases h with ⟨x, a, hy, hx, hk, hw, hnext⟩
    simp only [incItem] at hy
    simp only [hy]
    have hx : x = ⟨x.rule, x.position, x.startIdx, k⟩ := by
      simp only [bin, Set.mem_setOf_eq] at hx
      rw [← hx.right]
    apply EarleySet.scan hx (by grind) (by grind) (by grind) hnext
  else
    simp [hk] at h

public theorem predictFixpoint_sub_EarleySet (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (I : Set (EarleyItem T G.NT)) (k : Nat)
    (hsub : I ⊆ EarleySet G w) : predictFixpoint G I k ⊆ EarleySet G w := by
  intro y h
  simp only [predictFixpoint, Set.mem_setOf_eq] at h
  rcases h with ⟨x, r, hy, hmemy, hmemx, hnext⟩
  have hx : x = ⟨x.rule, x.position, x.startIdx, k⟩ := by
      simp only [bin, Set.mem_setOf_eq] at hmemx
      rw [← hmemx.right]
  rw [hy]
  apply EarleySet.predict hx (by grind) hmemy hnext

public theorem completeFixpoint_sub_EarleySet (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (I : Set (EarleyItem T G.NT)) (k : Nat)
    (hsub : I ⊆ EarleySet G w) : completeFixpoint I k ⊆ EarleySet G w := by
  intro z h
  simp only [completeFixpoint, Set.mem_setOf_eq] at h
  rcases h with ⟨x, y, hz, hmemx, hmemy, hcomp, hnext⟩
  have hx : x = ⟨x.rule, x.position, x.startIdx, y.startIdx⟩ := by
      simp only [bin, Set.mem_setOf_eq] at hmemx
      rw [← hmemx.right]
  have hy : y = ⟨y.rule, y.position, y.startIdx, k⟩ := by
    simp only [bin, Set.mem_setOf_eq] at hmemy
    rw [← hmemy.right]
  simp only [incItem] at hz
  simp only [hz]
  apply EarleySet.complete hx (by grind) hy (by grind) hcomp hnext

public theorem earleyFixpointBinStep_sub_EarleySet (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (k : Nat) {I : Set (EarleyItem T G.NT)}
    (hsub : I ⊆ EarleySet G w) : (earleyFixpointBinStep G w k) I ⊆ EarleySet G w := by
  simp only [earleyFixpointBinStep, Set.union_subset_iff]
  grind [scanFixpoint_sub_EarleySet, predictFixpoint_sub_EarleySet, completeFixpoint_sub_EarleySet]

public theorem earleyFixpointBin_sub_EarleySet (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (k : Nat) {I : Set (EarleyItem T G.NT)}
    (hsub : I ⊆ EarleySet G w) :
    earleyFixpointBin G w k I ⊆ EarleySet G w := by
  simp only [earleyFixpointBin]
  have := earleyFixpointBinStep_sub_EarleySet G w k hsub
  apply Limit.limit_upperbound
  · intro J hsub
    sorry
  · exact hsub

public theorem earleyFixpointBins_sub_EarleySet (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (k : Nat) :
    earleyFixpointBins G w k ⊆ EarleySet G w := by
  induction k with
  | zero => grind [initFixpoint_sub_EarleySet, earleyFixpointBin_sub_EarleySet]
  | succ n ih => grind [earleyFixpointBin_sub_EarleySet]

public theorem earleyFixpoint_sub_EarleySet (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) :
    earleyFixpoint G w ⊆ EarleySet G w := by
  apply earleyFixpointBins_sub_EarleySet G w w.length

public theorem soundnessEarleyFixpoint {G : ContextFreeGrammar T} [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] {w : List (Symbol T G.NT)} {x : EarleyItem T G.NT}
    (hmem : x ∈ earleyFixpoint G w) (hfin : isFinished G.initial w x) : G.Generates w := by
  grind [earleyFixpoint_sub_EarleySet, Model.soundnessEarley]

end Soundness

section Completeness

public theorem initFixpoint_sub_earleyFixpointBins (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (k : Nat) :
    initFixpoint G ⊆ earleyFixpointBins G w k := by
  induction k with
  | zero =>
    intro x hmem
    simp [earleyFixpointBins, earleyFixpointBin]
    sorry
  | succ n ih =>
    intro x hmem
    simp [earleyFixpointBins, earleyFixpointBin]
    sorry


public theorem EarleySet_sub_earleyFixpoint (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (hw : isWord G w) :
    EarleySet G w ⊆ earleyFixpoint G w := by
  sorry

public theorem completenessEarleyFixpoint (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (hw : isWord G w) (hgen : G.Generates w) :
    ∃ x ∈ earleyFixpoint G w, isFinished G.initial w x := by
  have := Model.completenessEarley hw hgen
  grind [EarleySet_sub_earleyFixpoint]

end Completeness

/--
The set of the model is identical to the one generated by the fixpoint algorithm.
-/
public theorem EarleySet_eq_earleyFixpoint (G : ContextFreeGrammar T) [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (hw : isWord G w) :
    EarleySet G w = earleyFixpoint G w := by
  have hsub1 := EarleySet_sub_earleyFixpoint G w hw
  have hsub2 := earleyFixpoint_sub_EarleySet G w
  apply Set.eq_of_subset_of_subset hsub1 hsub2

/--
The correctness criteria for the fixpoint version of the recognizer.

A word can be generated from the grammar
iff there exists a finished item within the corresponding fixpoint-iterated Set.
-/
public theorem correctnessEarleyFixpoint {G : ContextFreeGrammar T} [BEq T] [BEq G.NT]
    [LawfulBEq G.NT] (w : List (Symbol T G.NT)) (hw : isWord G w) : G.Generates w ↔
    ∃ x ∈ earleyFixpoint G w, isFinished G.initial w x := by
  grind [EarleySet_eq_earleyFixpoint, Model.correctnessEarleyModel]

end Fixpoint
end Proofs
end Earley
