/-
Copyright (c) 2026 Daniel Soukup. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Daniel Soukup
-/
module
public import Earley.Model
public import Earley.Slice
public import Earley.Derivation

/-!
This module houses the correctness proofs for the
  __  __           _      _
 |  \/  |         | |    | |
 | \  / | ___   __| | ___| |
 | |\/| |/ _ \ / _` |/ _ \ |
 | |  | | (_) | (_| |  __/ |
 |_|  |_|\___/ \__,_|\___|_|


The proofs follow the work from Rau et Nipkow:
https://doi.org/10.4230/LIPIcs.ITP.2024.31

To verify the correctness of the implementation,
we first prove correctness of the model - an inductive definition / judgements.
Then we can refine the proofs to a fixpoint-based implementation by proving
that the items in the Sets correspond exactly to the EarleyItems generated by the judgements,
then refine it further to the actual bins with the same idea.

TODO: Rename a ton of lemmas since I forgot about the style in the middle /o\
      https://leanprover-community.github.io/contribute/naming.html
-/

@[expose] public section

namespace Earley
namespace Proofs
namespace Model

open Earley.Model
open Earley.Model.EarleyItem
open Utils

variable {T N : Type}

/--
If the position of an `EarleyItem` is zero, then `alphaItem` of that item is empty.
-/
@[simp]
lemma alphaItem_of_zero (item : EarleyItem T N) (h : item.position = 0) :
    alphaItem item = [] := by
  simp [alphaItem, h]

/--
If the position of an `EarleyItem` is zero,
then `betaItem` of that item is the full output rule.
-/
@[simp]
lemma betaItem_of_zero (item : EarleyItem T N) (h : item.position = 0) :
    betaItem item = item.rule.output := by
  simp [betaItem, h]

/--
If the position of an `EarleyItem` is the length of the output of its rule,
then `alphaItem` of that item is the full output rule.
-/
@[simp]
lemma alphaItem_of_len (item : EarleyItem T N) (h : item.position = item.rule.output.length) :
    alphaItem item = item.rule.output := by
  simp [alphaItem, h]

/--
If the position of an `EarleyItem` is the length of the output of its rule,
then `betaItem` of that item is empty.
-/
@[simp]
lemma betaItem_of_len (item : EarleyItem T N) (h : item.position = item.rule.output.length) :
    betaItem item = [] := by
  simp [betaItem, h]

grind_pattern alphaItem_of_zero => alphaItem item, item.position
grind_pattern alphaItem_of_len => alphaItem item, item.position
grind_pattern betaItem_of_zero => betaItem item, item.position
grind_pattern betaItem_of_len => betaItem item, item.position

section WellFormed

/--
If there is a next symbol, then the position `pos+1` is still in bounds of the rhs of the rule.
-/
lemma bounds_of_nextSymbol_eq_some {G : ContextFreeGrammar T} {x : EarleyItem T G.NT}
    {a : Symbol T G.NT} (h : nextSymbol x = some a) : x.position + 1 ≤ x.rule.output.length := by
  rw [nextSymbol] at h
  have := of_getElem?_eq_some h
  omega

/--
Any EarleyItem within an EarleySet is well-formed.
TODO: maybe split these up like I did with `soundItemEarley`? only if I need them somewhere else
-/
public theorem wfEarley (G : ContextFreeGrammar T) [BEq G.NT] (w : List (Symbol T G.NT))
    (x : EarleyItem T G.NT) (hmem : x ∈ EarleySet G w) : isWellFormed G.rules w x := by
  unfold isWellFormed
  induction hmem with
  | init rule hmem hstart => grind
  | scan hx hmem hbounds hw hnext ih =>
    simp only
    have := bounds_of_nextSymbol_eq_some hnext
    simp only [hx] at ih this
    refine ⟨ih.left,this,by omega⟩
  | predict hx hmem hr2 hnext ih =>
    simp only
    simp only [hx] at ih
    refine ⟨hr2,by omega⟩
  | complete hx hmemx hy hmemy hcomp hnext ihx ihy =>
    simp only
    have := bounds_of_nextSymbol_eq_some hnext
    simp only [hx] at ihx this
    simp only [hy] at ihy
    refine ⟨ihx.left,this, by omega⟩

grind_pattern wfEarley => x ∈ EarleySet G w

end WellFormed

section Soundness
open ContextFreeRule
open ContextFreeGrammar

attribute [local grind cases] Rewrites
attribute [local grind .] Rewrites.input_output
-- these should probably be custom patterns
--attribute [grind <=] Rewrites.append_left
--attribute [grind <=] Rewrites.append_right
-- this is most likely not a good idea
--attribute [grind →] Rewrites.exists_parts
--attribute [grind =] rewrites_iff
attribute [local grind] Produces
attribute [local grind] Derives
attribute [local grind <=] Derives.trans
attribute [local grind <=] Derives.append_left
attribute [local grind <=] Derives.append_right
attribute [local grind] Generates

attribute [local grind =_] List.singleton_append
attribute [local grind =] List.getElem_cons_drop
attribute [local grind =] List.drop_add_one_eq_tail_drop

/--
An item (A → α • β, i, j) for a word w is sound, if
by starting the grammar at the input of the rule of the item (A)
you can derive the i'th up to but exluding the j'th symbol of the word
followed by the remaining beta.
-/
@[grind]
public def isSound (G : ContextFreeGrammar T) [BEq G.NT] (w : List (Symbol T G.NT))
    (item : EarleyItem T G.NT) : Prop :=
  let parsedAlpha := slice w item.startIdx item.endIdx
  G.Derives [Symbol.nonterminal item.rule.input] <| parsedAlpha ++ betaItem item

/--
Any well-formed EarleyItem within an EarleySet, where the position is zero, is sound
This is the case for the .init and .predict constructor.
Since the new item `A → •α, j, j` is at the beginning of the rule and w_j/j = [],
we only need to show that A derives α, which is exactly the rule.
-/
public theorem soundItemPosZero (G : ContextFreeGrammar T) [BEq G.NT] (w : List (Symbol T G.NT))
    {rule : ContextFreeRule T G.NT} {j : Nat} (hmem : rule ∈ G.rules) :
    isSound G w ⟨rule,0,j,j⟩ := by
  -- TODO: grind is able to prove this now, but probably wiser to keep the proof?
  unfold isSound
  simp only
  apply Produces.single
  use rule
  simp [hmem, Rewrites.input_output]

/--
Any EarleyItem within an EarleySet produced through the .scan constructor is sound.
Given item `A → α • a β, i, j` we can derive `A → α a • β, i, j+1`:
To prove soundness of the new item, we need to show A deriving w_i/j+1 ++ β
from A deriving w_i/j ++ (a :: β).
Since we know that the next symbol is `a`, this is mostly reasoning with slice/drop.
-/
public theorem soundItemScan (G : ContextFreeGrammar T) [BEq G.NT] (w : List (Symbol T G.NT))
    {x : EarleyItem T G.NT} {rule : ContextFreeRule T G.NT} {pos i j : Nat} {a : Symbol T G.NT}
    (hx : x = ⟨rule, pos, i, j⟩) (hmem : x ∈ EarleySet G w) (hbounds : j < w.length)
    (hw : w[j] = a) (hnext : nextSymbol x = some a) (hsound : isSound G w x) :
    isSound G w ⟨rule,pos+1,i,j+1⟩ := by
  -- TODO: grind is able to prove this now, but probably wiser to keep the proof?
  simp only [isSound, betaItem]
  simp only [isSound, betaItem, hx] at hsound
  simp only [nextSymbol, hx] at hnext
  -- Split the expected parse into w_i/j ++ [a]
  have wfx := wfEarley G w x hmem
  simp [isWellFormed, hx] at wfx
  have := slice_succ_right w wfx.right.right.left hbounds
  simp only [this, hw]
  -- Use the trailing [a] to get rid of the off by one
  have := getElem_of_getElem? hnext
  rcases this with ⟨hbounds,hpos⟩
  have := @List.getElem_cons_drop _ rule.output pos hbounds
  rw [hpos] at this
  simp only [List.append_assoc, List.cons_append, List.nil_append]
  rw [this]
  exact hsound

/--
Any EarleyItem within an EarleySet produced through the .complete constructor is sound.
Given item x `A → α • B β` and item y `B → γ •`, we can derive the item `A → α B • β`
with approriate indices. This proof operates like the one for .scan, but we have to chain
two substrings together: one for α and one for γ.
-/
public theorem soundItemComplete (G : ContextFreeGrammar T) [BEq G.NT] (w : List (Symbol T G.NT))
    {x y : EarleyItem T G.NT} {rule1 rule2 : ContextFreeRule T G.NT} {posx posy i j k : Nat}
    (hx : x = ⟨rule1, posx, i, j⟩) (hmemx : x ∈ EarleySet G w)
    (hy : y = ⟨rule2, posy, j, k⟩) (hmemy : y ∈ EarleySet G w)
    (hcomp : isComplete y) (hnext : nextSymbol x = some (Symbol.nonterminal rule2.input))
    (hsoundx : isSound G w x) (hsoundy : isSound G w y) :
    isSound G w ⟨rule1,posx+1,i,k⟩ := by
  simp only [isSound, betaItem]
  simp only [isSound, betaItem, hx, hy] at hsoundx hsoundy
  simp [isComplete, hy] at hcomp
  simp only [hcomp, List.drop_length, List.append_nil] at hsoundy
  -- Derive using the first rule
  apply Derives.trans hsoundx
  have : slice w i j ++ slice w j k = slice w i k := by grind
  rw [← this]
  -- Remove matching Prefix
  rw [List.append_assoc]
  apply Derives.append_left _ (slice w i j)
  -- Pop out the non-terminal for rule2/y
  simp only [nextSymbol, hx] at hnext
  have := getElem_of_getElem? hnext
  rcases this with ⟨hbounds,hpos⟩
  have := @List.getElem_cons_drop _ rule1.output posx hbounds
  grind

/--
Any EarleyItem within an EarleySet is sound.
-/
public theorem soundItemEarley (G : ContextFreeGrammar T) [BEq G.NT] (w : List (Symbol T G.NT))
    (x : EarleyItem T G.NT) (hmem : x ∈ EarleySet G w) : isSound G w x := by
  induction hmem with
  | init _ hmem =>
    exact soundItemPosZero _ _ hmem
  | scan hx hmem hbounds hw hnext ih =>
    exact soundItemScan _ _ hx hmem hbounds hw hnext ih
  | predict hx hmemx hmemr2 hnext =>
    exact soundItemPosZero _ _ hmemr2
  | complete hx hmemx hy hmemy hcomp hnext ihx ihy =>
    exact soundItemComplete _ _ hx hmemx hy hmemy hcomp hnext ihx ihy

/--
The soundness criteria for the EarleySet:
Given a finished item for a word within the set, the grammar has to be able to generate that word.
-/
public theorem soundnessEarley {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    {w : List (Symbol T G.NT)} {x : EarleyItem T G.NT} (hmem : x ∈ EarleySet G w)
    (hfin : isFinished G.initial w x) : G.Generates w := by
  have := soundItemEarley G w x hmem
  unfold Generates
  simp only [isFinished, isComplete, Bool.and_eq_true, beq_iff_eq] at hfin
  simp only [isSound, hfin, slice_length, betaItem, List.drop_length, List.append_nil] at this
  exact this

end Soundness

section Completeness
open ContextFreeRule
open ContextFreeGrammar

/--
A set of EarleyItems {(A → α • β, i, j)} w.r.t to a word `w` is partially complete up to `n`, if
for i ≤ j ≤ n every item in the set `(A → α • a β, i, j)` and
every derivation from `a` to w_j/n,
the set also contains the item `(A → α a • β, i, k)`.

Basicly if there is Derivation within the indices that progresses the word,
the corresponding progressed item has to be within the set as well.

Crucially, there exists a predicate `P` which the Derivation has to uphold.
This is to limit the length of the Derivation.
-/
public def isPartiallyComplete (G : ContextFreeGrammar T) [BEq G.NT] (w : List (Symbol T G.NT))
    (n : Nat) (I : Set (EarleyItem T G.NT)) (P : List (ContextFreeRule T G.NT) → Bool) : Prop :=
  ∀ (rule : ContextFreeRule T G.NT) (pos i j k : Nat) {x : EarleyItem T G.NT} {a : Symbol T G.NT}
    {D : List (ContextFreeRule T G.NT)},
    j ≤ k ∧ k ≤ n ∧ n ≤ w.length ∧ x = ⟨rule, pos, i, j⟩ ∧ x ∈ I ∧
    nextSymbol x = some a ∧ Derivation G [a] D (slice w j k) ∧ P D
    → ⟨rule, pos+1, i, k⟩ ∈ I

/--
If we know the set to be partially complete without restrictions,
then we also know the set to be partially complete for a restricted Derivation length.
-/
lemma partiallyComplete_of_unrestricted_partiallyComplete {G : ContextFreeGrammar T} [BEq G.NT]
    {w : List (Symbol T G.NT)} {n : Nat} {I : Set (EarleyItem T G.NT)}
    {D : List (ContextFreeRule T G.NT)} (hcomp : isPartiallyComplete G w n I (fun _ => true)) :
    isPartiallyComplete G w n I (fun D' => D'.length ≤ D.length) := by
  grind [isPartiallyComplete]

/--
If we know the set to be partially complete for a given Derivation length,
then we also know the set to be partially complete for a further restricted Derivation length .
-/
lemma partiallyComplete_of_longer_partiallyComplete {G : ContextFreeGrammar T} [BEq G.NT]
    {w : List (Symbol T G.NT)} {n : Nat} {I : Set (EarleyItem T G.NT)}
    {E F : List (ContextFreeRule T G.NT)} (hlen : F.length ≤ E.length)
    (hcomp : isPartiallyComplete G w n I (fun D => D.length ≤ E.length)) :
    isPartiallyComplete G w n I (fun D => D.length ≤ F.length) := by
  grind [isPartiallyComplete]

/--
If a set of EarleyItems is partially complete up to `n`, then given a progressable item,
the progressed item is also within the set.
See `isPartiallyComplete`.
-/
lemma partiallyCompleteUpTo (G : ContextFreeGrammar T) [BEq G.NT] (w : List (Symbol T G.NT))
    (n : Nat) (I : Set (EarleyItem T G.NT))
    {pos i j : Nat} {A : G.NT} {α : List (Symbol T G.NT)} {D : List (ContextFreeRule T G.NT)}
    (hjn : j ≤ n) (hlen : n ≤ w.length) (x : EarleyItem T G.NT) (hx : x = ⟨⟨A, α⟩, pos, i, j⟩)
    (hmem : x ∈ I) (wfI : ∀ x ∈ I, isWellFormed G.rules w x)
    (hD : Derivation G (betaItem x) D (slice w j n))
    (hcomp : isPartiallyComplete G w n I (fun D' => D'.length ≤ D.length)) :
    ⟨⟨A, α⟩, α.length, i, n⟩ ∈ I := by
  induction hbeta : betaItem x generalizing pos i j n A D α x with
  | nil =>
    -- `A → α • []`: the position is given and the item is already complete.
    have hpos : pos = α.length := by
      simp [betaItem, hx] at hbeta
      have := wfI x hmem
      simp [isWellFormed, hx] at this
      omega
    simp only [betaItem, hx, hpos, List.drop_length] at hD
    have : slice w j n = [] := Derivation_of_empty_input G hD
    have heq : j = n := by
      simp [slice_eq_droptake] at this
      omega
    rw [heq, hpos] at hx
    rw [hx] at hmem
    apply hmem
  -- `A → α • a β`:
  | cons r rs ih =>
    rw [hbeta] at hD
    simp only [betaItem, hx] at hbeta
    have wfX := wfI x hmem
    simp [isWellFormed, hx] at wfX
    rw [← List.singleton_append] at hD
    -- Split the Derivation into a single step and the rest
    have := Derivation_cons_split G hD
    rcases this with ⟨a',b',E,F,⟨hE,hF,hab,hlenE,hlenF⟩⟩
    have : ∃ k, a' = slice w j k ∧ b' = slice w k n ∧ j ≤ k ∧ k ≤ n:= slice_concat_ex hab hjn
    rcases this with ⟨k,⟨ha',hb',hjk,hkn⟩⟩
    simp only [ha', hb'] at hE hF
    -- Construct an EarleyItem part of the Set, where the next symbol has been parsed
    let y : EarleyItem T G.NT := ⟨⟨A,α⟩, pos+1, i, k⟩
    have hnextx : nextSymbol x = some r := by
      simp [nextSymbol, hx]
      have := @List.getElem_cons_drop _ α pos (by grind)
      grind
    have hmemy : y ∈ I := by
      simp only [isPartiallyComplete, decide_eq_true_eq, and_imp] at hcomp
      apply hcomp ⟨A,α⟩ pos i j k (by omega) (by omega) (by omega) hx hmem hnextx hE hlenE
    have hrs : betaItem y = rs := by
      simp only [betaItem, y]
      have := @List.drop_add_one_eq_tail_drop _ pos α
      simp [this, hbeta]
    have wfY := wfI y hmemy
    simp [isWellFormed, y] at wfY
    -- Apply the IH for that Item
    have ih := @ih n (pos+1) i k A α F hkn hlen y (by simp [y]) hmemy
    apply ih
    · simp [hrs, hF]
    · apply partiallyComplete_of_longer_partiallyComplete hlenF hcomp
    · simp [hrs]

/--
The EarleySet is partially complete.
-/
lemma partiallyCompleteEarley (G : ContextFreeGrammar T) [BEq G.NT] (w : List (Symbol T G.NT))
    (n : Nat) : isPartiallyComplete G w n (EarleySet G w) (fun _ => true) := by
  intro rule pos i j k x a D ⟨hjk, hkn, hlen, hx, hmemx, hnext, hD, hP⟩
  induction hDlen : D.length using Nat.strong_induction_on generalizing rule pos i j k x a D with
  | h m ih =>
    cases D with
    | nil =>
      simp at hDlen
      simp only [Derivation_of_empty_rule] at hD
      have hkw : k ≤ w.length := by omega
      have hkj : k = j + 1 := by
        have : [a].length = 1 := by simp
        rw [hD] at this
        exact succ_of_len w j k this hkw
      have hlenj : j < w.length := by omega
      have : w[j] = a := by
        have := @slice_one _ w j (by omega)
        simp [hkj, this] at hD
        simp [hD]
      rw [hkj]
      apply EarleySet.scan hx hmemx hlenj this hnext
    | cons r rs =>
      simp only [Derivation_succ] at hD
      rcases hD.right with ⟨u, hu⟩
      -- We know that the next symbol `a` has to be a non-terminal.
      -- For completeness we therefore have to prove that a .complete EarleyItem
      -- with the next symbol handled exists within the EarleySet.
      cases a
      · cases hu.left
        rename_i hrs
        cases hrs
      next A =>
      -- Thus we need to construct the items which handle the metasymbol `A` fully.
      let y : EarleyItem T G.NT := ⟨⟨A,u⟩, 0, j, j⟩
      have : rs.length < (r::rs).length := by simp
      have hcompn : isPartiallyComplete G w n (EarleySet G w) (fun F => F.length ≤ rs.length) := by
        grind [isPartiallyComplete]
      have hcompk : isPartiallyComplete G w k (EarleySet G w) (fun F => F.length ≤ rs.length) := by
        grind [isPartiallyComplete]
      have hrs : Derivation G (betaItem y) rs (slice w j k) := by
        simp only [betaItem, List.drop_zero, y]
        exact hu.right
      have hmemy : y ∈ EarleySet G w := by
        simp only [y]
        have hr := rule_of_rewrite_step G r hu.left
        rw [hr] at hD
        apply EarleySet.predict hx hmemx hD.left hnext
      -- Through partial completeness of y, we know that there is a complete version of y,
      -- which we can use in combination with x for a completion rule
      let z : EarleyItem T G.NT := ⟨⟨A,u⟩, u.length, j, k⟩
      have hmemz : z ∈ EarleySet G w := by
        apply partiallyCompleteUpTo G w k (EarleySet G w)
          (by omega) (by omega) y _ hmemy (wfEarley G w) hrs hcompk
        · exact 0
        · simp [y]
      apply EarleySet.complete (rule2 := ⟨A,u⟩) (posy := u.length) hx hmemx
        (by simp [z]) hmemz (by simp [isComplete, z]) hnext

/--
The completeness criteria for the EarleySet:
Given a word the grammar can generate,
there has to be a finished item within the corresponding EarleySet.
-/
public theorem completenessEarley {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    {w : List (Symbol T G.NT)} (hw : isWord G w) (hgen : G.Generates w) :
    ∃ x ∈ EarleySet G w, isFinished G.initial w x := by
  simp only [isFinished, isComplete, Bool.and_eq_true, beq_iff_eq]
  -- Fetch the first rule that has to have been applied
  have := derives_implies_Derivation hgen
  rcases this with ⟨D,hD⟩
  have := Derivation_step G w hw D hD
  rcases this with ⟨u,D',hu⟩
  -- Create the initial EarleyItem, which is on the critical path
  let x : EarleyItem T G.NT := ⟨⟨G.initial, u⟩, 0, 0, 0⟩
  have hx : x = ⟨⟨G.initial, u⟩, 0, 0, 0⟩ := by simp [x]
  have hmemx : x ∈ EarleySet G w := by
    apply EarleySet.init x.rule hu.right
    simp [hx]
  -- The remaining Derivation links the initial item with the final item via partial completeness
  have hD' : Derivation G u D' (slice w 0 w.length) := by simp [hu.left]
  have partCompShorter :
      isPartiallyComplete G w w.length (EarleySet G w) (fun D => D.length ≤ D'.length) := by
    have partComp := partiallyCompleteEarley G w w.length
    apply partiallyComplete_of_unrestricted_partiallyComplete partComp
  -- Prove a finished EarleyItem exists by fully leaning on EarleySet being partially completed
  have : ⟨⟨G.initial, u⟩, u.length, 0, w.length⟩ ∈ EarleySet G w := by
    exact partiallyCompleteUpTo G w w.length (EarleySet G w)
      (by omega) (by omega) x hx hmemx (wfEarley G w) hD' partCompShorter
  use ⟨⟨G.initial, u⟩, u.length, 0, w.length⟩

end Completeness

/--
The correctness criteria for the EarleySet.

A word can be generated from the grammar
iff there exists a finished item within the corresponding EarleySet.
-/
public theorem correctnessEarleyModel {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    {w : List (Symbol T G.NT)} (hw : isWord G w) :
    G.Generates w ↔ ∃ x ∈ EarleySet G w, isFinished G.initial w x := by
  constructor
  · apply completenessEarley hw
  · intro hex
    rcases hex with ⟨hw,h⟩
    apply soundnessEarley h.left h.right

end Model
end Proofs
end Earley
