/-
Copyright (c) 2026 Daniel Soukup. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Daniel Soukup
-/
module
public import Mathlib.Data.Set.Finite.Basic
public import Mathlib.Data.Set.Finite.Powerset
public import Mathlib.Data.Finite.Prod
public import Earley.Model
public import Earley.Proofs.Model
public import Earley.Slice
public import Earley.Derivation
public import Earley.Recognizer
public import Earley.Proofs.Finiteness

/-!
This module houses the correctness proofs for the
  _      _     _              _____                 _
 | |    (_)   | |            |_   _|               | |
 | |     _ ___| |_   ______    | |  _ __ ___  _ __ | |
 | |    | / __| __| |______|   | | | '_ ` _ \| '_ \| |
 | |____| \__ \ |_            _| |_| | | | | | |_) | |
 |______|_|___/\__|          |_____|_| |_| |_| .__/|_|
                                             | |
                                             |_|

The proofs follow the work from Rau et Nipkow:
https://doi.org/10.4230/LIPIcs.ITP.2024.31

To verify the correctness of the implementation,
we first prove correctness of the model - an inductive definition / judgements.
Then we can refine the proofs to a fixpoint-based implementation by proving
that the items in the Sets correspond exactly to the EarleyItems generated by the judgements,
then refine it further to the actual bins with the same idea.

TODO: Rename a ton of lemmas since I forgot about the style in the middle /o\
      https://leanprover-community.github.io/contribute/naming.html
TODO: think about where or if to stop using List T for w
TODO: order of i j k k' is a mess since there is heavy overlap.
      Need to choose unique ident for everything.
TODO: remove usage of w solely for Vec length
-/

@[expose] public section

set_option linter.unusedSectionVars false

namespace Earley
namespace Proofs
namespace Recognizer

open Earley.Model
open Earley.Model.EarleyItem
open Earley.Proofs.Model
open Earley.Recognizer
open Earley.Proofs.Finiteness
open Utils
open ContextFreeRule
open ContextFreeGrammar

variable {T N : Type} [BEq T] [LawfulBEq T] [BEq N] [LawfulBEq N] [LawfulBEq (EarleyItem T N)]

@[grind]
def setOfBins {n : Nat} (bins : EarleyBins T N n) : Set (EarleyItem T N) :=
  { x | ∃ k, ∃ (hk : k < n), x ∈ items bins[k] }

-- TODO: unused, unclear if this restriction will be relevant for some induction proof
@[grind]
def setOfBinsK {n : Nat} (bins : EarleyBins T N n) (m : Nat) (hm : m < n) : Set (EarleyItem T N) :=
  { x | ∃ k, ∃ (hk : k ≤ m), x ∈ items bins[k] }

-- While `= k` might seem more direct, `≤ k` helps with the induction on the elements within the set
-- I need to be able to showcase that the original items also exist in that set, and they can have
-- lower endIdx
@[grind]
def setOfModelK (G : ContextFreeGrammar T) (w : List T) (k : Nat) : Set (EarleyItem T G.NT) :=
  { x | x ∈ EarleySet G (mapT w) ∧ x.endIdx ≤ k}

@[grind]
def earleyListSet (G : ContextFreeGrammarList T N) (w : List T) : Set (EarleyItem T N) :=
  earleyList G w |>.bins |> setOfBins

@[grind →]
lemma binIdx_of_endIdx (G : ContextFreeGrammarList T N) (w : List T)
    {bins : EarleyBins T N (w.length + 1)} (hbins : isWellFormedBins G w bins)
    (x : EarleyItem T N) {k : Nat} (hk : k < w.length + 1)
    (hmem : x ∈ items bins[k]) : k = x.endIdx := by
  grind

section Subsets

theorem updateBinAux_IsPrefix (xs : List (BinItem T N)) (y : BinItem T N) :
    List.IsPrefix (items xs) (items (updateBinAux xs y)) := by
  induction xs generalizing y with
  | nil => grind
  | cons x xs ih => grind

theorem updateBinAux_extensive (xs : List (BinItem T N)) (y : BinItem T N) :
    items xs ⊆ items (updateBinAux xs y) :=
  List.IsPrefix.subset (updateBinAux_IsPrefix xs y)

theorem updateBinAuxY_extensive (xs : List (BinItem T N)) (y : BinItem T N) :
    y.item ∈ items (updateBinAux xs y) := by
  induction xs generalizing y with
  | nil => grind
  | cons x xs ih => grind

theorem updateBin_IsPrefix (xs ys : List (BinItem T N)) :
    List.IsPrefix (items xs) (items (updateBin xs ys)) := by
  induction ys generalizing xs with
  | nil => grind
  | cons y ys ih => grind [updateBinAux_IsPrefix]

theorem updateBin_extensive (xs ys : List (BinItem T N)) : items xs ⊆ items (updateBin xs ys) :=
  List.IsPrefix.subset (updateBin_IsPrefix xs ys)

theorem updateBinY_extensive (xs ys : List (BinItem T N)) : items ys ⊆ items (updateBin xs ys) := by
  induction ys generalizing xs with
  | nil => grind
  | cons y ys ih => grind [updateBinAuxY_extensive, updateBin_extensive]

theorem updateBins_IsPrefix {w : List T} {bins : EarleyBins T N (w.length + 1)} (i k : Nat)
    (hi : i < w.length + 1) (hk : k < w.length + 1) (newBin : List (BinItem T N)) :
    List.IsPrefix (items bins[i]) (items (updateBins bins k newBin hk)[i]) := by
  grind [updateBin_IsPrefix]

lemma updateBins_extensive {w : List T} {bins : EarleyBins T N (w.length + 1)}
    (k i : Nat) (hk : k < w.length + 1) (hi : i < w.length + 1) (newBin : List (BinItem T N)) :
    items bins[i] ⊆ items (updateBins bins k newBin hk)[i] :=
  List.IsPrefix.subset (updateBins_IsPrefix i k hi hk newBin)

lemma updateBinsNewBin_extensive {w : List T} {bins : EarleyBins T N (w.length + 1)}
    (k : Nat) (hk : k < w.length + 1) (newBin : List (BinItem T N)) :
    items newBin ⊆ items (updateBins bins k newBin hk)[k] := by
  grind [updateBinY_extensive]

lemma setOfBinsUpdateBins_extensive {w : List T} {bins : EarleyBins T N (w.length + 1)}
    (k : Nat) (hk : k < w.length + 1) (newBin : List (BinItem T N)) :
    setOfBins bins ⊆ setOfBins (updateBins bins k newBin hk) := by
  grind [updateBins_IsPrefix]

theorem earleyBinList_IsPrefix {G : ContextFreeGrammarList T N} {w : List T}
    {bins : EarleyBins T N (w.length + 1)} (hbins : isWellFormedBins G w bins)
    (k j i : Nat) (hk : k < w.length + 1) (hi : i < w.length + 1) :
    List.IsPrefix (items bins[i]) (items (earleyBinList G w k bins hk j hbins).bins[i]) := by
  fun_induction earleyBinList G w k bins hk j hbins with
  | case1 bins hk j hbins hj => grind
  | case2 bins hk j hbins hj x bins' hbins' => grind [updateBins_IsPrefix]

lemma earleyBinList_extensive {G : ContextFreeGrammarList T N} {w : List T}
    {bins : EarleyBins T N (w.length + 1)} (hbins : isWellFormedBins G w bins)
    (k j i : Nat) (hk : k < w.length + 1) (hi : i < w.length + 1) :
    items bins[i] ⊆ items (earleyBinList G w k bins hk j hbins).bins[i] :=
  List.IsPrefix.subset (earleyBinList_IsPrefix hbins k j i hk hi)

-- todo: unclear if this helps with earleyBinListJ_sub_earleyBinList or is even easier to prove.
lemma earleyBinList_sub_earleyBinList {G : ContextFreeGrammarList T N} {w : List T}
    {bins bins' : EarleyBins T N (w.length + 1)} (hbins : isWellFormedBins G w bins)
    (hbins' : isWellFormedBins G w bins')
    (m k j : Nat) (hm : m < w.length + 1) (hk : k < w.length + 1)
    (hsub : ∀ i, ∃ (hi : i < w.length + 1), items bins[i] ⊆ items bins'[i]) :
    items (earleyBinList G w m bins hm j hbins).bins[k] ⊆
    items (earleyBinList G w m bins' hm 0 hbins').bins[k] := by
  sorry

-- I could prove it more general, but I need it like this
-- FIXME: this is actually quite troublesome huh
-- maybe I need some sublist property?
-- maybe I should do two different lemmas since G w m [k] is only required for scan?
lemma earleyBinListJ_sub_earleyBinList {G : ContextFreeGrammarList T N} {w : List T}
    {bins : EarleyBins T N (w.length + 1)} (hbins : isWellFormedBins G w bins)
    (m k j : Nat) (hm : m < w.length + 1) (hk : k < w.length + 1) :
    items (earleyBinList G w m bins hm j hbins).bins[k] ⊆
    items (earleyBinList G w m bins hm 0 hbins).bins[k] := by
  induction j generalizing bins with
  | zero => grind
  | succ n ih =>
    apply subset_trans _ (ih hbins)
    clear ih
    intro x hmem
    rw [earleyBinList]
    if hj : n ≥ bins[m].length then
      simp [ge_iff_le, hj, ↓reduceDIte]
      have : n + 1 ≥ bins[m].length := by omega
      rw [earleyBinList] at hmem
      simp [this] at hmem
      grind [earleyBinList_extensive]
    else
      simp [hj]
      --have := earleyBinList_sub_earleyBinList
      sorry

lemma setOfBinsEarleyBinList_extensive {G : ContextFreeGrammarList T N} {w : List T}
    {bins : EarleyBins T N (w.length + 1)} (hbins : isWellFormedBins G w bins)
    (k j : Nat) (hk : k < w.length + 1) :
    setOfBins bins ⊆ setOfBins (earleyBinList G w k bins hk j hbins).bins := by
  fun_induction earleyBinList G w k bins hk j hbins with
  | case1 bins hk j hbins hj => grind
  | case2 bins hk j hbins hj x bins' hbins' =>
    rename_i ih
    apply subset_trans _ ih
    clear ih
    simp only [ge_iff_le, bins']
    match hnext : x.item.nextSymbol with
    | none => apply setOfBinsUpdateBins_extensive k hk
    | some s =>
      match hS : s with
      | .terminal t =>
        if hw : w.length ≤ k then
          simp [hw]
        else
          simp only [hw, ↓reduceDIte]
          apply setOfBinsUpdateBins_extensive (k+1)
      | .nonterminal n => apply setOfBinsUpdateBins_extensive k hk

section Unused
-- I think I should never reason on that level about extensive ?

lemma earleyBinsList_extensiveAux (G : ContextFreeGrammarList T N) (w : List T) (k n : Nat)
    (hi : k ≤ n) (hk : n < w.length) {x : EarleyItem T N}
    (hmem : x ∈ items (earleyBinsList G w n (by lia)).bins[k]) :
    x ∈ items (earleyBinsList G w (n+1) (by lia)).bins[k] := by
  grind [earleyBinList_extensive]

lemma earleyBinsList_extensive (G : ContextFreeGrammarList T N) (w : List T) (k n m : Nat)
    (hk : k ≤ n) (hn : n ≤ m) (hm : m < w.length + 1) {x : EarleyItem T N}
    (hmem : x ∈ items (earleyBinsList G w n (by lia)).bins[k]) :
    x ∈ items (earleyBinsList G w m (by lia)).bins[k] := by
  induction m with
  | zero =>
    grind [earleyBinsList_extensiveAux]
  | succ m ih =>
    if h : n = m+1 then
      grind
    else
      specialize ih (by grind) (by lia) hmem
      apply earleyBinsList_extensiveAux G w k m (by lia) (by lia) ih

end Unused

lemma updateBinAux_sub {s : Set (EarleyItem T N)} (xs : List (BinItem T N)) (y : BinItem T N)
    (hx : {x | x ∈ items xs} ⊆ s) (hy : y.item ∈ s) :
    {z | z ∈ items (updateBinAux xs y) } ⊆ s := by
  induction xs generalizing y with
  | nil => grind
  | cons x xs ih => grind

lemma updateBin_sub {s : Set (EarleyItem T N)} (xs ys : List (BinItem T N))
    (hx : {x | x ∈ items xs} ⊆ s) (hy : {y | y ∈ items ys} ⊆ s) :
    {z | z ∈ items (updateBin xs ys) } ⊆ s := by
  induction ys generalizing xs with
  | nil => grind
  | cons y ys ih => grind [updateBinAux_sub]

lemma updateBins_sub {w : List T} {bins : EarleyBins T N (w.length + 1)}
    {s : Set (EarleyItem T N)} (hb : setOfBins bins ⊆ s)
    (newBin : List (BinItem T N)) (k : Nat) (hk : k < w.length + 1)
    (hn : {y | y ∈ items newBin} ⊆ s) : setOfBins (updateBins bins k newBin hk) ⊆ s := by
  intro z hmemz
  simp only [setOfBins, Order.lt_add_one_iff, Set.mem_setOf_eq] at hmemz
  rcases hmemz with ⟨i,hi,hmem⟩
  if heq : i = k then
    have hb : {x | x ∈ items bins[k]} ⊆ s := by
      intro x hmemx
      apply hb
      simp only [setOfBins, Order.lt_add_one_iff, Set.mem_setOf_eq]
      use k, by lia
      apply hmemx
    have := updateBin_sub bins[k] newBin hb hn
    have hmem : z ∈ {z | z ∈ items (updateBin bins[k] newBin)} := by grind
    apply Set.mem_of_mem_of_subset hmem this
  else
    grind

end Subsets

section Soundness

-- TODO: maybe this should be/there should exist initBins_sub_model hm.
-- Not sure if I require that result more than once
lemma initList_sub_Model {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] (w : List T) {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) : { x | x ∈ items (initList Gₗ)} ⊆ EarleySet G (mapT w) := by
  intro x hmem
  simp only [items, initList, List.map_map, List.mem_map, List.mem_filter, beq_iff_eq,
    Function.comp_apply, Set.mem_setOf_eq] at hmem
  rcases hmem with ⟨r,hmemr,hx⟩
  have hmemx : r ∈ G.rules := by grind [Finset.mem_toList]
  have hstart : r.input = G.initial := by grind
  rw [← hx]
  apply EarleySet.init r hmemx hstart

-- TODO: unclear if its better to refactor the operations into separate proofs
lemma earleyBinListSet_sub_model {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] (w : List T) {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) (bins : EarleyBins T G.NT (w.length + 1))
    (hbins : isWellFormedBins Gₗ w bins) (hsub : setOfBins bins ⊆ EarleySet G (mapT w))
    (k j : Nat) (hk : k < w.length + 1) :
    setOfBins (earleyBinList Gₗ w k bins hk j hbins).bins ⊆ EarleySet G (mapT w) := by
  fun_induction earleyBinList Gₗ w k bins hk j hbins with
  | case1 bins hk j hbins hj => grind [earleyBinList]
  | case2 bins hk j hbins hj x bins' hbins' =>
    rename_i ih
    apply ih
    simp only [ge_iff_le, bins']
    clear ih hbins' bins'
    match hnext : x.item.nextSymbol with
    | none =>
      simp only
      apply updateBins_sub hsub
      rename' x => y
      -- x is the original item to be completed, y isComplete, z is the completed item
      intro z
      simp only [items, completeList, incItem, List.map_map, List.mem_map, Function.comp_apply,
        Prod.exists, exists_and_right, Set.mem_setOf_eq, map_of_mapT, forall_exists_index, and_imp]
      intro x xIdx hF hz
      have hcomp : y.item.isComplete = true := by
        clear hF hz hsub
        grind
      have := mem_of_memFilterWithIdx hF
      have hx : x.item = ⟨x.item.rule, x.item.position, x.item.startIdx, y.item.startIdx⟩ := by
        have : x.item.endIdx = y.item.startIdx := by grind
        rw [← this]
      have hmemx : x.item ∈ EarleySet G (List.map Symbol.terminal w) := by
        apply Set.mem_of_mem_of_subset (by grind) hsub
      have hE : y.item.endIdx = k := by grind
      have hy : y.item = ⟨y.item.rule, y.item.position, y.item.startIdx, k⟩ := by rw [← hE]
      have hmemy : y.item ∈ EarleySet G (List.map Symbol.terminal w) := by
        apply Set.mem_of_mem_of_subset (by grind) hsub
      have hnext : x.item.nextSymbol = some (Symbol.nonterminal y.item.rule.input) := by
        have := P_of_filterWithIdx (bins[y.item.startIdx]'(by grind)) (fun x : BinItem T G.NT =>
          x.item.nextSymbol == some (Symbol.nonterminal y.item.rule.input)) hF
        simp only [beq_iff_eq] at this
        apply this
      rw [← hz]
      rw [hE]
      apply EarleySet.complete hx hmemx hy hmemy hcomp hnext
    | some s =>
      match hS : s with
      | .terminal t =>
        if hw : w.length ≤ k then
          simp [hw, hsub]
        else
          simp only [hw, ↓reduceDIte]
          apply updateBins_sub hsub
          if ht : w[k] = t then
            simp only [items, scanList, ht, BEq.rfl, ↓reduceIte, incItem, List.map_cons,
              List.map_nil, List.mem_cons, List.not_mem_nil, or_false, Set.setOf_eq_eq_singleton,
              map_of_mapT, Set.singleton_subset_iff]
            apply EarleySet.scan (by simp) (by grind) (by grind) (by grind) hnext
          else
            simp [items, scanList, ht]
      | .nonterminal n =>
        simp only
        apply updateBins_sub hsub
        intro y
        simp only [items, predictList, List.map_map, List.mem_map, List.mem_filter, beq_iff_eq,
          Function.comp_apply, Set.mem_setOf_eq, map_of_mapT, forall_exists_index, and_imp]
        intro r hmemr hr hy
        have hx : x.item = ⟨x.item.rule, x.item.position, x.item.startIdx, k⟩ := by
          have : x.item.endIdx = k := by grind
          rw [← this]
        rw [← hy]
        rw [← hr] at hnext
        have : r ∈ G.rules := by grind [Finset.mem_toList]
        apply EarleySet.predict hx (by grind) this hnext

lemma earleyBinListZeroSet_sub_model {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] (w : List T) {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) (bins : EarleyBins T G.NT (w.length + 1))
    (hbins : isWellFormedBins Gₗ w bins) (k : Nat) (hk : k < w.length + 1)
    (hsub : setOfBins bins ⊆ EarleySet G (mapT w)) :
    setOfBins (earleyBinList Gₗ w k bins hk 0 hbins).bins ⊆ EarleySet G (mapT w) := by
  grind [earleyBinListSet_sub_model]

lemma earleyBinsListSet_sub_model {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] (w : List T) {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) (k : Nat) (hk : k < w.length + 1) :
    setOfBins (earleyBinsList Gₗ w k hk).bins ⊆ EarleySet G (mapT w) := by
  induction k with
  | zero =>
    simp only [earleyBinsList]
    intro x hmem
    let wfBins := initBins Gₗ w
    have : setOfBins wfBins.bins ⊆ EarleySet G (mapT w) := by
      simp only [setOfBins, Order.lt_add_one_iff, map_of_mapT, wfBins]
      intro x hmem
      rcases hmem with ⟨k,hk,hmem⟩
      grind [initList_sub_Model w h]
    apply earleyBinListZeroSet_sub_model w h wfBins.bins wfBins.inv 0 (by simp) this (by grind)
  | succ k ih =>
    intro x hmem
    let hbins := (earleyBinsList Gₗ w k (by lia)).inv
    apply earleyBinListZeroSet_sub_model w h (earleyBinsList Gₗ w k (by lia)).bins hbins (k+1)
    · intro y hmemy
      have := ih (by lia)
      apply Set.mem_of_mem_of_subset hmemy this
    · simp only [earleyBinsList] at hmem
      grind [setOfBinsEarleyBinList_extensive]
    · lia

lemma earleyListSet_sub_model {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] (w : List T) {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) : earleyListSet Gₗ w ⊆ EarleySet G (mapT w) := by
  simp only [earleyListSet, earleyList]
  have := earleyBinsListSet_sub_model w h w.length (by lia)
  grind

/--
The soundness criteria for the list implementation:
Given a finished item for a word within the set, the grammar has to be able to generate that word.
-/
public theorem soundnessEarleyList {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] (w : List T) {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) (hex : recognizeList Gₗ w) : G.Generates (mapT w) := by
  simp only [recognizeList, decide_eq_true_eq] at hex
  rcases hex with ⟨x, ⟨hmem, hfin⟩⟩
  have := earleyListSet_sub_model w h
  apply soundnessEarley (x := x)
  · have : {x | x ∈ items (earleyList Gₗ w).bins[w.length]}
        ⊆ {x | x ∈ items (Vector.toList (earleyList Gₗ w).bins).flatten} := by
      intro x hmem
      grind [Vector.mem_toList_iff]
    grind [Vector.mem_toList_iff, Set.setOf_subset_setOf]
  · grind

end Soundness

-- soundItemEarley G w x hmemx
lemma false_of_impossibleCompletedItem {G : ContextFreeGrammar T} [BEq G.NT] {x : EarleyItem T G.NT}
    {w : List (Symbol T G.NT)} (heps : isEpsilonFree G) (hsound : isSound G w x)
    (hs : x.startIdx = x.endIdx) (hcomp : x.isComplete) : False := by
  have : nonEmptyDerives G := nonEmptyDerives_of_isEpsilonFree heps
  grind

section Completeness

lemma initModel_sub_initL {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) {r : ContextFreeRule T G.NT} (hmemr : r ∈ G.rules)
    (hr : r.input = G.initial) : ⟨r,0,0,0⟩ ∈ items (initList Gₗ) := by
  simp only [items, initList, List.map_map, List.mem_map, List.mem_filter, beq_iff_eq,
    Function.comp_apply, EarleyItem.mk.injEq, and_self, and_true, exists_eq_right]
  grind [Finset.mem_toList]

lemma initModel_sub_earleyBinListZero {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] {Gₗ : ContextFreeGrammarList T G.NT} (w : List T)
    (h : CFGEqCFGₗ G Gₗ) {r : ContextFreeRule T G.NT} (hmem : r ∈ G.rules)
    (hr : r.input = G.initial) : ⟨r,0,0,0⟩ ∈
    items (earleyBinList Gₗ w 0 (initBins Gₗ w).bins (by simp) 0 (by grind)).bins[0] := by
  have hsub := initModel_sub_initL h hmem hr
  let wfBins := initBins Gₗ w
  let wfBins' := earleyBinList Gₗ w 0 wfBins.bins (by simp) 0 wfBins.inv
  have : items wfBins.bins[0] ⊆ items wfBins'.bins[0] := by
    apply earleyBinList_extensive (hi := by simp)
  apply @Set.mem_of_mem_of_subset _ ⟨r,0,0,0⟩ _ _ hsub this

lemma scanMem_of_earleyBinListIndex {G : ContextFreeGrammarList T N} {w : List T}
    {bins : EarleyBins T N (w.length + 1)} (hbins : isWellFormedBins G w bins)
    (k j : Nat) (hk : k < w.length) (hj : ¬ (j ≥ bins[k].length))
    {x : EarleyItem T N} (hx : x = bins[k][j].item) (a : T)
    (hnext : bins[k][j].item.nextSymbol = some (Symbol.terminal a)) :
    items (scanList w x a k (by grind) j) ⊆
    items ((earleyBinList G w k bins (by lia) j hbins).bins[k+1]'(by grind)) := by
  intro y hmemy
  rw [earleyBinList]
  have : ¬ (w.length ≤ k) := by grind
  simp only [ge_iff_le, this, hj, ↓reduceDIte, hnext]
  have : y ∈ items (updateBins bins (k+1) (scanList w x a k (by lia) j) (by grind))[k+1] := by
    grind [updateBinsNewBin_extensive]
  have : isWellFormedBins G w
      (updateBins bins (k+1) (scanList w x a k (by lia) j) (by grind)) := by
    grind [wfBins_of_earleyBinList]
  have : y ∈ items (earleyBinList G w k (updateBins bins (k+1) (scanList w x a k (by lia) j)
      (by lia)) (by lia) (j + 1) this).bins[k+1] := by grind [earleyBinList_extensive]
  grind

lemma scanModel_sub_scanL {G : ContextFreeGrammarList T N} {w : List T}
    {bins : EarleyBins T N (w.length + 1)} (hbins : isWellFormedBins G w bins)
    {pos i : Nat} {r : ContextFreeRule T N} {a : Symbol T N} (k : Nat) (hk : k < w.length)
    {x : EarleyItem T N} (hx : x = ⟨r, pos, i, k⟩) (hmem : x ∈ items bins[k])
    (hnext : x.nextSymbol = some a) (hw : (mapT w)[k]'(by grind) = a) :
    ⟨r, pos+1, i, k+1⟩ ∈
    items ((earleyBinList G w k bins (by lia) 0 hbins).bins[k+1]'(by grind)) := by
  -- TODO: Should've went with w : List T in the model as well. But for now, no need to change.
  have : ∃ a', a = Symbol.terminal a' := by grind
  rcases this with ⟨a, ha⟩
  -- Get the index of x to showcase that the call upon that item triggers scanX
  have := List.getElem_of_mem hmem
  rcases this with ⟨j, hjI, heq⟩
  -- x = bins[k][j]
  have hmemT : ⟨r, pos+1, i, k+1⟩ ∈ items (scanList w x a k (by lia) j) := by
    simp [scanList, items]
    grind
  have : items (scanList w x a k (by lia) j) ⊆
      items (earleyBinList G w k bins (by lia) 0 hbins).bins[k + 1] := by
    have hj' : ¬ (j ≥ bins[k].length) := by grind
    have heq' : x = bins[k][j].item := by grind
    have hbins' := (earleyBinList G w k bins (by lia) 0 hbins).inv
    -- 0 is simply a superset of j, so extendable!
    have hscanJ := scanMem_of_earleyBinListIndex hbins k j (by lia) hj' heq' a (by grind [scanList])
    have hJ0 := earleyBinListJ_sub_earleyBinList hbins k (k+1) j (by lia) (by lia)
    apply subset_trans hscanJ hJ0
  apply Set.mem_of_mem_of_subset hmemT this (x := ⟨r, pos+1, i, k+1⟩)

lemma predictMem_of_earleyBinListIndex {G : ContextFreeGrammarList T N} {w : List T}
    {bins : EarleyBins T N (w.length + 1)} (hbins : isWellFormedBins G w bins)
    (k j : Nat) (hk : k < w.length + 1) (hj : ¬ (j ≥ bins[k].length))
    (A : N) (hnext : bins[k][j].item.nextSymbol = some (Symbol.nonterminal A)) :
    items (predictList G A k) ⊆
    items ((earleyBinList G w k bins (by lia) j hbins).bins[k]'(by grind)) := by
  intro y hmemy
  rw [earleyBinList]
  simp only [ge_iff_le, hj, ↓reduceDIte, hnext]
  have : y ∈ items (updateBins bins k (predictList G A k) (by grind))[k] := by
    grind [updateBinsNewBin_extensive]
  have : isWellFormedBins G w (updateBins bins k (predictList G A k) (by grind)) := by
    grind [wfBins_of_earleyBinList]
  have : y ∈ items (earleyBinList G w k (updateBins bins k (predictList G A k) (by lia))
    (by lia) (j + 1) this).bins[k] := by grind [earleyBinList_extensive]
  grind

-- (ih : x ∈ items ((earleyBinList Gₗ w k bins (by lia) 0 hbins).bins[k]'(by grind))) :
-- maybe? at some point I will require earleyBinList_idem I think.
lemma predictModel_sub_predictL {G : ContextFreeGrammarList T N} {w : List T}
    {bins : EarleyBins T N (w.length + 1)} (hbins : isWellFormedBins G w bins)
    {k : Nat} {r2 : ContextFreeRule T N} {x : EarleyItem T N} (hk : k < w.length + 1)
    (ih : x ∈ items bins[k]) (hmemr2 : r2 ∈ G.rules)
    (hnext : x.nextSymbol = some (Symbol.nonterminal r2.input)) :
    ⟨r2, 0, k, k⟩ ∈ items ((earleyBinList G w k bins (by lia) 0 hbins).bins[k]'(by grind)) := by
  -- Get the index of x to showcase that the call upon that item triggers predictX
  have := List.getElem_of_mem ih
  rcases this with ⟨j, hjI, heq⟩
  -- x = bins[k][j]
  have hmemT : ⟨r2, 0, k, k⟩ ∈ items (predictList G r2.input k) := by
    simp [predictList, items]
    grind
  have : items (predictList G r2.input k) ⊆
      items (earleyBinList G w k bins (by lia) 0 hbins).bins[k] := by
    have hj' : ¬ (j ≥ bins[k].length) := by grind
    have heq' : x = bins[k][j].item := by grind
    have hbins' := (earleyBinList G w k bins (by lia) 0 hbins).inv
    have := predictMem_of_earleyBinListIndex hbins k j (by lia) hj' r2.input (by grind)
    -- 0 is simply a superset of j, so extendable!
    have hJ0 := earleyBinListJ_sub_earleyBinList hbins k k j (by lia) (by lia)
    apply subset_trans this hJ0
  apply Set.mem_of_mem_of_subset hmemT this (x := ⟨r2, 0, k, k⟩)

lemma completeModel_sub_completeL {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] {w : List T} {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) (hw : isWord G (mapT w)) (heps : isEpsilonFree G)
    {bins : EarleyBins T G.NT (w.length + 1)} (hbins : isWellFormedBins Gₗ w bins)
    {posx posy i j k : Nat} {r1 r2 : ContextFreeRule T G.NT} {x y : EarleyItem T G.NT}
    (hk : k < w.length + 1) (hx : x = ⟨r1, posx, i, j⟩) (hy : y = ⟨r2, posy, j, k⟩)
    (hmemx : x ∈ EarleySet G (mapT w)) (hmemy : y ∈ EarleySet G (mapT w))
    (hmemxL : x ∈ items (bins[j]'(by grind))) (hmemyL : y ∈ items (bins[k]'(by grind)))
    (hnext : x.nextSymbol = some (Symbol.nonterminal r2.input)) (hcomp : y.isComplete = true) :
    ⟨r1, posx+1, i, k⟩ ∈
    items ((earleyBinList Gₗ w k bins (by lia) 0 hbins).bins[k]'(by grind)) := by
  let targetItem : EarleyItem T G.NT := ⟨r1, posx+1, i, k⟩
  let newItemsFromX := completeList y bins (by grind) j
  -- x = bins[k][j], but here x = bins[j][unknown yet]
  have : targetItem ∈ items newItemsFromX := by
    simp only [items, completeList, List.map_map, List.mem_map, Function.comp_apply, Prod.exists,
      exists_and_right, newItemsFromX, targetItem]
    -- I want to use `x` and its index within bins[j] aka i
    -- requiring a BinItem could be an issue?
    -- Check/need a lemma that I get filterWithIdx from mem from which
    -- I can rcases the actual idx and binitem?
    use ⟨x,Pointer.null⟩
    refine ⟨?_, by grind⟩
    use 0
    --grind [Finset.mem_toList]
    sorry
  sorry

lemma modelKZero_sub_earleyBinsListZeroSet {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] (w : List T) {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) (hw : isWord G (mapT w)) (heps : isEpsilonFree G)
    {x : EarleyItem T G.NT} (hmemx : x ∈ EarleySet G (mapT w)) (hke : x.endIdx = 0) :
    x ∈ items (earleyBinsList Gₗ w 0 (by lia)).bins[0] := by
  induction hmemx with
  | init r hmem hr => exact initModel_sub_earleyBinListZero w h hmem hr
  -- There cant be a valid item generated through .scan in the first bin.
  | scan hx hmem hbounds hw hnext ih => grind
  | predict hx hmemx hmemr2 hnext ih =>
    rename_i x r1 r2 pos i j
    specialize ih (by grind)
    simp only at hke
    rw [hke]
    rw [hke] at hx
    let wfBins := initBins Gₗ w
    -- FIXME: so .. this usage is obv wrong
    have : x ∈ items wfBins.bins[0] := by sorry
    have := predictModel_sub_predictL wfBins.inv (by lia) this (by grind [Finset.mem_toList]) hnext
    sorry
  -- There can't exist a valid item generated through .complete in the first bin:
  -- since the grammar is epsilon free, there has to be at least a terminal consumed for a rule to
  -- be completed.
  | complete hx hmemx hy hmemy hcomp hnext hmemx_ih hmemy_ih =>
    rename_i x y r1 r2 posx posy i j k
    have : isSound G (mapT w) y := by grind [soundItemEarley]
    have := false_of_impossibleCompletedItem heps this (by grind)
    grind

lemma modelK_sub_earleyBinsListSet {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] (w : List T) {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) (hw : isWord G (mapT w)) (heps : isEpsilonFree G)
    {bins : EarleyBins T G.NT (w.length + 1)} (hbins : isWellFormedBins Gₗ w bins)
    (k : Nat) (hk : k < w.length) (hsub : setOfModelK G w k ⊆ setOfBins bins) :
    setOfModelK G w (k + 1) ⊆
    setOfBins (earleyBinList Gₗ w (k + 1) bins (by lia) 0 hbins).bins := by
  simp only [setOfModelK, map_of_mapT, setOfBins, Order.lt_add_one_iff, Set.setOf_subset_setOf,
    and_imp]
  intro x hmemx hke
  induction hmemx with
  | init r hmem hr =>
    use 0, by lia
    simp only [setOfModelK, setOfBins, Order.lt_add_one_iff, Set.setOf_subset_setOf] at hsub
    have : ⟨r,0,0,0⟩ ∈ EarleySet G (List.map Symbol.terminal w) := EarleySet.init r hmem hr
    specialize hsub ⟨r,0,0,0⟩ ⟨this, by grind⟩
    rcases hsub with ⟨k',hk',hmem'⟩
    have : ⟨r,0,0,0⟩ ∈ items bins[0] := by grind
    apply earleyBinList_extensive hbins (k+1) 0 0 (by lia) (by lia) this
  -- We want to show ⟨r,pos+1,i,j+1⟩ ∈ bins[j+1] from x ∈ bins[j] w/ x=⟨r,pos,i,j⟩
  | scan hx hmem hbounds hw hnext ih =>
    rename_i x r pos i j a
    use j+1, (by lia)
    specialize ih (by grind)
    rcases ih with ⟨k', hk', ih⟩
    let inv := (earleyBinList Gₗ w (k + 1) bins (by lia) 0 hbins).inv
    -- maybe I need to do
    have hmem : x ∈ items (earleyBinList Gₗ w (k + 1) bins (by lia) 0 hbins).bins[j] := by grind
    have := scanModel_sub_scanL inv j (by lia) hx hmem hnext hw
    -- need some extensive lemma here
    sorry
  -- We want to show ⟨r2,0,j,j⟩ ∈ bins[j] from x ∈ bins[j] w/ x=⟨r1,pos,i,j⟩
  | predict hx hmemx hmemr2 hnext ih =>
    rename_i x r1 r2 pos i j
    use j, by lia
    specialize ih (by grind)
    rcases ih with ⟨k', hk', ih⟩
    let inv := (earleyBinList Gₗ w (k + 1) bins (by lia) 0 hbins).inv
    -- FIXME: this usage is obv wrong
    have : x ∈ items bins[j] := by sorry
    have := predictModel_sub_predictL hbins (by lia) this (by grind [Finset.mem_toList])
      hnext (k := j)
    sorry
  -- We want to show z=⟨r1,posx+1,i,kz⟩ ∈ bins[kz] from
  -- - x ∈ bins[j]  w/ x=⟨r1,posx,i,j⟩
  -- - y ∈ bins[kz] w/ y=⟨r2,posy,j,kz⟩
  | complete hx hmemx hy hmemy hcomp hnext ihx ihy =>
    rename_i x y r1 r2 posx posy i j kz
    use kz, by lia
    specialize ihx (by grind)
    specialize ihy (by grind)
    rcases ihx with ⟨kx, hkx, ihx⟩
    rcases ihy with ⟨ky, hky, ihy⟩
    let inv := (earleyBinList Gₗ w (k + 1) bins (by lia) 0 hbins).inv
    -- FIXME: obviously I cant use it like that. Need to split on kz being equal to k+1?
    --        else the ih has to handle it.
    have := completeModel_sub_completeL h hw heps inv (by grind) hx hy
      hmemx hmemy (by grind) (by grind) hnext hcomp
    sorry

lemma modelK_sub_earleyListSetK {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] (w : List T) {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) (hw : isWord G (mapT w)) (heps : isEpsilonFree G)
    (k : Nat) (hk : k < w.length + 1) :
    setOfModelK G w k ⊆ setOfBins (earleyBinsList Gₗ w k hk).bins := by
  induction k with
  | zero =>
    simp only [setOfModelK, setOfBins, Order.lt_add_one_iff, Set.setOf_subset_setOf, and_imp]
    intro x hmemx hke
    use 0, (by lia)
    apply modelKZero_sub_earleyBinsListZeroSet w h hw heps hmemx (by lia)
  | succ k ih =>
    specialize ih (by grind)
    let hbins := (earleyBinsList Gₗ w k (by lia)).inv
    apply modelK_sub_earleyBinsListSet w h hw heps hbins k (by lia) ih

lemma model_sub_earleyListSet {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] (w : List T) {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) (hw : isWord G (mapT w)) (heps : isEpsilonFree G) :
    EarleySet G (mapT w) ⊆ earleyListSet Gₗ w := by
  intro x hmem
  simp only [earleyListSet, setOfBins, earleyList, Order.lt_add_one_iff, Set.mem_setOf_eq]
  have := modelK_sub_earleyListSetK w h hw heps
  simp only [Order.lt_add_one_iff, setOfModelK, map_of_mapT, setOfBins, Set.setOf_subset_setOf,
    and_imp] at this
  grind

lemma model_eq_earleyListSet {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] (w : List T) {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) (hw : isWord G (mapT w)) (heps : isEpsilonFree G) :
    EarleySet G (mapT w) = earleyListSet Gₗ w := by
  have h1 := model_sub_earleyListSet w h hw heps
  have h2 := earleyListSet_sub_model w h
  apply subset_antisymm h1 h2

public theorem completenessEarleyList {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] (w : List T) {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) (hw : isWord G (mapT w)) (heps : isEpsilonFree G)
    (hgen : G.Generates (mapT w)) : recognizeList Gₗ w := by
  simp only [recognizeList, decide_eq_true_eq]
  -- Select a relevant finished item from the Model Proof
  have hc := completenessEarley hw hgen
  rcases hc with ⟨x, hmemx, hfin⟩
  use x
  -- Use the fact that the set of items generated by the model are the same as the impl
  have heq := model_eq_earleyListSet w h hw heps
  rw [heq] at hmemx
  simp only [earleyListSet, setOfBins, Order.lt_add_one_iff, Set.mem_setOf_eq] at hmemx
  rcases hmemx with ⟨k, hk, hmemx⟩
  -- Well-formedness proves that that item has to reside within the final bin
  let hbins := (earleyList Gₗ w).inv
  grind

end Completeness

/--
The correctness criteria for the recognizer.
A word can be generated from the grammar iff the algorithm recognizes the word.
-/
public theorem correctnessEarleyList {G : ContextFreeGrammar T} [BEq G.NT] [LawfulBEq G.NT]
    [LawfulBEq (EarleyItem T G.NT)] (w : List T) {Gₗ : ContextFreeGrammarList T G.NT}
    (h : CFGEqCFGₗ G Gₗ) (hw : isWord G (mapT w)) (heps : isEpsilonFree G) :
    G.Generates (mapT w) ↔ recognizeList Gₗ w := by
  grind [soundnessEarleyList, completenessEarleyList]

end Recognizer
end Proofs
end Earley
